.PHONY: run test lint migrate-up migrate-down docker-up docker-down

run:
	go run ./cmd/server

test:
	go test ./...

lint:
	go vet ./...

migrate-up:
	migrate -path migrations -database "$$DATABASE_URL" up

migrate-down:
	migrate -path migrations -database "$$DATABASE_URL" down 1

docker-up:
	docker compose -f docker/docker-compose.yml up --build

docker-down:
	docker compose -f docker/docker-compose.yml down
